### ISSUE TITLE
Please update verions bot

### ISSUE THREAD

**Issue by Billty09** [darkdaddy/Lineage2RevBot#7]
Weekly Quest must "Wrong Completion Detected"
 SearchPixel Failed: 112.11 x 198.656 => 0xC1CCD9
 SearchPixel OK: 112.11 x 198.656 => OK 721 x 234, 0xCD945D

Sometimes successful But the bot does not pass.
Sorry english bad, i'm play thailand server
I like use bot you

**Comment by iampandz** [comment]
scroll quest also fail > wrong pos

how to find the correct position to update?

**Comment by KagerouXD** [comment]
Dear Billty09,
Can you show us how did you get the pixel and coordinates for the buttons?
Thanks.
